### ISSUE TITLE
Error: uudecode: stdin: No `begin' line

### ISSUE THREAD

**Issue by fresheneesz** [zacbarton/node-uuencode#3]
I'm using linux's uudecode to decode data produced by node-uuencode and it tells me
   uudecode: stdin: No `begin' line

Are there difference versions of uuencode/uudecode? Why's the begin line not part of node-uuencode's output?

**Comment by zacbarton** [comment]
@fresheneesz your'e correct that this module doesn't currently produce the header and footer sections but the encoded/decoded values are valid.

If you wrap this modules output with a header and footer the results will be the same as the command line utility. Note that I've added a test to confirm this.

**Comment by fresheneesz** [comment]
Could you please document this fact on the readme?
